### PR TITLE
Gradle bintray deployment

### PR DESCRIPTION
**Pull request by samhandev**
This switches to a Gradle only build.

It also always you to deploy your `jar` to `bintray` so that you can include the library as a dependency in `pom.xml` /  `build.gradle`.

### CODE REVIEW

**Comment by StephenHynes7** [comment]
@samhandev  any chance you can resubmit without the jar file? Just don't want to accept a jar file.

**Comment by samhandev** [comment]
Hey @StephenHynes7, do you mean the `lib/logentries-android.jar` file?
If so, that has actually been removed in this commit.

**Comment by StephenHynes7** [comment]
No https://github.com/samhandev/le_android/blob/22d72d4e20271d48f182879a586e27cdca166c93/gradle/wrapper/gradle-wrapper.jar,after that ill be happy to merge this.

**Comment by samhandev** [comment]
Ah just spotted that 👍 .
I've done another commit to remove the `gradle wrapper` files.

You can regenerate then using the command:
`gradle wrapper`

**Comment by cheffernan-r7** [comment]
Hey @samhandev with your changes could please explain how a new user would add this library to a project? Thanks.

**Comment by samhandev** [comment]
@cheffernan-r7 
Do you mean uploading this to a new project in `bintray`?

or adding it to your android project?

**Comment by cheffernan-r7** [comment]
@samhandev thanks for the reply. Just not sure how the gradle-bintray setup works. For example how would I add this le_android library to an existing project in Android studio?

**Comment by samhandev** [comment]
@cheffernan-r7 
They way it's set up now is to deploy the library to `bintray`.
In my case I an uploading the generated library to an organisation called `mnscorp`
https://bintray.com/mnscorp/maven/le-android

Then I need to have the following in my android `build.gradle` file:
This is to tell gradle where to find to search for any dependancies
```
repositories {
    maven {
        url  "http://dl.bintray.com/mnscorp/maven" 
    }
}
```
This is the actual dependancy:
```
compile 'com.logentries:logentries-android:3.0.3'
```

You might want to set up an organisation in `bintray` for `logentries` and then make a `local.properties` file with you `bintray` details. (There is a `local.properties.example` file in the repo to get you started)

I have added some details about this in the README but it probably needs to be fleshed out.

**Comment by cheffernan-r7** [comment]
@samhandev ok sounds good, we will look into it. Thanks for the info

**Pull request merged**
